version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgres://postgres:postgres@db/weather_dev"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
