version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/weather_dev
      - SECRET_KEY_BASE=xb9446iJgJtqheH4wK7Hv3L/2F36X0paIO7marOmKjnktE8ZEToCOkEA7TzQbL4x
      - PORT=4000
      - DATABASE_HOST=db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_dev