apiVersion: v1
kind: Service
metadata:
  name: weatherapp
spec:
  type: LoadBalancer
  selector:
    app: weatherapp
  ports:
  - port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  selector:
    matchLabels:
      app: weatherapp
  replicas: 2
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
        - name: weatherapp
          image: kirega/weather_web:latest
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY_BASE
              value: "xb9446iJgJtqheH4wK7Hv3L/2F36X0paIO7marOmKjnktE8ZEToCOkEA7TzQbL4x"
            - name: DATABASE_URL
              value: "ecto://postgres:postgres@db/weather_dev"
            - name: PORT
              value: "8080"
            - name: DATABASE_HOST
              value: "db"
            - name: DB_USER
              value: "postgres"
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:alpine3.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "weather_dev"
          resources:
            limits:
              cpu: "400m"
              memory: "128Mi"
