apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weatherapp.fullname" . }}
  labels:
    {{- include "weatherapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: {{ .Values.appname }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version}}"
          ports:
            - containerPort: {{ .Values.service.weather.port }}
          envFrom:
          - secretRef:
              name: "env-config"
          env:
          - name: PORT
            value: {{ .Values.service.weather.port | quote}}

          - name: DATABASE_HOST
            value: {{ .Values.service.postgres.name }}

          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.postgres.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.service.postgres.name }}
          image: postgres:alpine3.16
          ports:
            - containerPort: {{ .Values.service.postgres.port }}
          envFrom:
          - secretRef:
              name: env-config
          resources:
            limits:
              cpu: "400m"
              memory: "128Mi"
