apiVersion: v1
kind: Service
metadata:
  name: {{ include "weatherapp.fullname" . }}
  labels:
    {{- include "weatherapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.weather.type }}
  ports:
    - port: {{ .Values.service.weather.port }}
  selector:
    app: {{ .Values.appname }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.postgres.name }}
spec:
  type: {{ .Values.service.postgres.type }}
  ports:
    - port: {{ .Values.service.postgres.port }}
  selector:
    app: {{ .Values.service.postgres.name }}